/**
 * Subscription-invoice HTML renderer — ported verbatim from
 * src/shared/documents/vetan-invoice-html.ts (NestJS).
 *
 * Lightweight self-contained HTML for the "download invoice" endpoint
 * (`GET /v1/billing/invoices/:invoiceId/download`). Inlined CSS so the
 * browser print-to-PDF path renders standalone.
 */
export function buildVetanInvoiceHtml(opts: {
  tenantName: string;
  tenantSlug: string;
  periodLabel: string;
  amountInr: number;
  currency: string;
  paidAt: string | null;
  invoiceId: string;
  status: string;
}): string {
  const statusDisplay = opts.status.replace(/_/g, " ");
  const paidLine = opts.paidAt
    ? `<p class="muted">Paid on: <strong>${opts.paidAt}</strong></p>`
    : "";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Vetan Invoice — ${opts.periodLabel}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 640px; margin: 2rem auto; color: #2f3035; }
    h1 { font-size: 1.25rem; margin-bottom: 0.25rem; color: #f87941; }
    .muted { color: #b1b1b1; font-size: 0.875rem; }
    .status { margin: 0.75rem 0; padding: 0.5rem 0.75rem; background: #fff0e8; border-radius: 6px; font-size: 0.875rem; border: 1px solid #f9b095; }
    table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; }
    th, td { text-align: left; padding: 0.5rem 0; border-bottom: 1px solid #e6e4e6; }
    .total { font-size: 1.125rem; font-weight: 600; color: #f87941; }
    footer { margin-top: 2rem; font-size: 0.75rem; color: #b1b1b1; }
  </style>
</head>
<body>
  <h1>Vetan Platform Invoice</h1>
  <p class="muted">Workspace: ${opts.tenantName} (${opts.tenantSlug})</p>
  <p class="muted">Invoice ID: ${opts.invoiceId}</p>
  <p class="muted">Billing period: <strong>${opts.periodLabel}</strong></p>
  <div class="status">Status: <strong>${statusDisplay}</strong></div>
  ${paidLine}
  <table>
    <thead><tr><th>Description</th><th>Amount</th></tr></thead>
    <tbody>
      <tr>
        <td>Vetan subscription — ${opts.periodLabel}</td>
        <td>${opts.currency} ${opts.amountInr.toLocaleString("en-IN")}</td>
      </tr>
    </tbody>
  </table>
  <p class="total">Total: ${opts.currency} ${opts.amountInr.toLocaleString("en-IN")}</p>
  <footer>Generated by Vetan. This document reflects subscription billing recorded in your workspace.</footer>
</body>
</html>`;
}
